apiVersion: v1
kind: Secret
metadata:
  name: actualbudget-export-secret
  namespace: actualbudget
type: Opaque
stringData:
  ACTUAL_SERVER_URL: ""
  ACTUAL_PASSWORD: ""
  ACTUAL_BUDGET_NAME: "Expenses"
  ACTUAL_EXPORT_BASE_DIR: "/app/export"
